### PR TITLE
Updated API calls

### PR DESCRIPTION
**Pull request by anlek**
Hey,
I've just gone through Freshbook's API calls and updated the source to match.
For more info, please checkout the updated History.txt.

Only thing that still needs to be done is the Client credits have an attribute for currency, haven't figured out how to pull that into the credit object.

### CODE REVIEW

**Comment by tensiondriven** [comment]
Nice work Anlek!

**Comment by meceo** [comment]
@bcurren could you please have a look on this pull request?

**Comment by johnpray** [comment]
+1

**Comment by calebhaye** [comment]
+1

**Comment by bcurren** [comment]
Just merged into master. This looks great. Can't believe it took so long for me to merge.

**Pull request closed without merging**
